icc:
	icc -o test -O3 test.c -fopenmp
	icc -o ex01 -O3 ex01.c -fopenmp
	icc -o ex02 -O3 ex02.c -fopenmp
	icc -o ex03 -O3 ex03.c -fopenmp
	icc -o ex04 -O3 ex04.c -fopenmp
	icc -o ex05 -O3 ex05.c -fopenmp
	icc -o ex06 -O3 ex06.c -fopenmp
	icc -o ex07 -O3 ex07.c -fopenmp

gcc:
	gcc -o test -O4 test.c -fopenmp
	gcc -o ex01 -O3 ex01.c -fopenmp
	gcc -o ex02 -O3 ex02.c -fopenmp
	gcc -o ex03 -O3 ex03.c -fopenmp
	gcc -o ex04 -O3 ex04.c -fopenmp
	gcc -o ex05 -O3 ex05.c -fopenmp
	gcc -o ex06 -O3 ex06.c -fopenmp
	gcc -o ex07 -O3 ex07.c -fopenmp

clean:
	rm test
	rm ex01
	rm ex02
	rm ex03
	rm ex04
	rm ex05
	rm ex06
	rm ex07
