icc:
	icc -o benchmark -O3 Benchmark.c
	icc -D DOUBLE -o benchmark_double -O3 Benchmark.c
gcc:
	gcc -o benchmark -O4 Benchmark.c
	gcc -D DOUBLE -o benchmark_double -O4 Benchmark.c
clean:
	rm benchmark
